### ISSUE TITLE
Universal introduction

### ISSUE THREAD

**Issue by ionescu** [adamdejl/pithosnd#8]
Dear Adam,

I'm having problems with the universal introduction form.  For example, I'm trying to prove ∀xQ(x) from the premiss ∀x(P(x) ∧ Q(x)).  When I select the goal  and click on ∀I, I get a box with "x" as the goal, instead of ∀xQ(x) (see attached image).  I am then unable to prove "x".

Any suggestions for how to deal with this?  Many thanks for your help!

Best wishes,
Cezar.

![univintro](https://user-images.githubusercontent.com/2735802/97905105-bf083d00-1d41-11eb-9a18-36807f864bd1.png)

**Comment by adamdejl** [comment]
Hello Cezar,

I believe it is necessary to add additional brackets to the goal formula so that the parser can correctly differentiate between the variable `x` and the relation `Q`. In `∀xQ(x)`, `xQ` is assumed to be the universally quantified variable while `x` is expected to be an atom. This behaviour allows users to choose arbitrary names for the quantified variables.

To resolve the issue, the goal formula should be bracketed as `∀x[Q(x)]`.

**Comment by ionescu** [comment]
Dear Adam,

Thanks, I understand.  Yes, you are right: it works fine.

Best wishes,
Cezar
